### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dylanfoster** [dylanfoster/parch#1]
- [x] Controller action mapping (i.e. map controller action to its restul route partner)
- [x] Full restify options support
- [x] Default middleware set
  - [x] CORS
  - [x] acceptParser
  - [x] authenticationParser
  - [x] bodyParser
  - [x] fullResponse
  - [x] gzipResponse
  - [x] queryParser
- [x] Add default controller and model locations
- [x] Sequelize integration
- [x] Logger
- [x] Authentication/Authorization (jwt)
- [x] Querying support
- [ ] Pagination support
- [x] namespace support

**Comment by dylanfoster** [comment]
Moving pagination to its own issue
